### ISSUE TITLE
`prop` to `bool` 

### ISSUE THREAD

**Issue by nrryuya** [LayerXcom/cbc-casper-proof#11]
This makes error.
```
(* Definition 7.12 *)
definition majority_driven :: "all_validators ⇒ weight ⇒ estimator ⇒ consensus_value_property ⇒ bool"
  where
    "majority_driven all_v_set w e p = (∀ s. majority all_v_set w (agreeing p s) s ⟹ ∀ c. c ∈ e w s ∧ p c)"
```

prop: ∀ a. p ==> ∀ b. q
bool: ∀ a c. p --> q

**Comment by myuon** [comment]
This is a bit complicated but thinking about the difference between metalogic and hol is alway important.

| metalogic | hol | meaning |
|--|--|--|
| prop | bool | the result of formula |
| `==>` | `-->` | implication operator, having the type `prop => prop => prop` and `bool => bool => bool` |
| `\forall` | `!!` | forall, universal quantifier |

**NB** Isabelle will cast bool to prop implicitly.
**NB** Be careful about the parsing priorities of the operators `==>` and `-->`. E.g.) `\forall x. A ==> B` will be parsed as `(\forall x. A) ==> B`.

**Comment by nrryuya** [comment]
@myuon Thank you so much!

I guess `\forall` is HOL's and `!!` is Metalogic's?

**Comment by myuon** [comment]
Oops, my mistake! I fixed it.
