### ISSUE TITLE
`⇒` or `∧` ?

### ISSUE THREAD

**Issue by nrryuya** [LayerXcom/cbc-casper-proof#3]
Which is better, `x1 ∧ x2 ∧ ... ∧ xn` or `x1 ⇒ x2 ⇒ ... xn`? 

https://github.com/pirapira/cbc_casper/blob/master/BetsAndValidators.thy#L475
```
lemma consensus_safety :
  "finite b0 \<Longrightarrow>
   finite b1 \<Longrightarrow>
   is_non_empty b1 \<Longrightarrow>
   positive_weights (observed_validators b0) w \<Longrightarrow>
   positive_weights (observed_validators b1) w \<Longrightarrow>
   tie_breaking (observed_validators (b0 \<union> b1)) w \<Longrightarrow>
   is_estimate_safe w b0 e0 \<Longrightarrow>
   is_estimate_safe w b1 e1 \<Longrightarrow>
   consistent_views w b0 b1 \<Longrightarrow>
   e0 = e1
  "
```

**Comment by myuon** [comment]
Basically they are equivalent through currying, but technically I think `==>` form is better. If you have a lemma `lem: A ==> B ==> C` and an instance `val: A`, you can get a new term `B ==> C` by `lem [OF val]`. Like this example, implication form has some advantages.
Also, if you want to chain many implications, there is a handy notation: `[| A; B; C |] ==> D`

**Comment by nrryuya** [comment]
Thank you!
