### ISSUE TITLE
[Isabelle] `UN x:A. B` isn't parsed 

### ISSUE THREAD

**Issue by nrryuya** [LayerXcom/cbc-casper-proof#31]
![image](https://user-images.githubusercontent.com/22876645/51005830-d500a880-1583-11e9-8792-0ebb91b5bd79.png)

https://isabelle.in.tum.de/dist/Isabelle2018/doc/prog-prove.pdf

However, this definition of `Messages` is not parsed.

```
fun 
  Σ_i :: "params ⇒ nat ⇒ state set" and
  M_i :: "params ⇒ nat ⇒ message set"
  where 
    "Σ_i params 0 = {∅}"
  | "Σ_i params n = {σ ∈ Pow (M_i params (n - 1)). ∀ m. m ∈ σ ⟶ justification m ⊆ σ}"
  | "M_i params n = {m. est m ∈ C params ∧ sender m ∈ V params ∧ justification m ∈ (Σ_i params n) ∧ est m ∈ ε params (justification m)}" 

fun Messages :: "params ⇒ message set"
  where
    "Messages params = ⋃ i: ℕ. (M_i params)"
```

**Comment by nrryuya** [comment]
Workaround
```
fun Messages :: "params ⇒ message set"
  where
    "Messages params = {m. ∃ i ∈ ℕ. m ∈ M_i params i}"
```

**Comment by yudetamago** [comment]
Another solution by using image function (`)?

```isabelle
fun Messages :: "params ⇒ message set"
  where
    "Messages params = ⋃ (M_i params ` ℕ)"
end
```

**Comment by myuon** [comment]
Have you noticed `x \in A` in the document is subscripted? This actually requires you to write as a subscription. To input those subscriptions or superscriptions, use control blocks. You can input through the unicode symbol panel in the bottom in jEdit or you can take a look at `Isabelle/jEdit` reference for more information.

**Comment by myuon** [comment]
Sorry, I've misunderstood this. `⋃i∈ℕ. M_i params i` is the correct form.
