### ISSUE TITLE
[Isabelle] We can use `linorder ` or `preorder` type class in the proof of lemma 9 ?

### ISSUE THREAD

**Issue by yudetamago** [LayerXcom/cbc-casper-proof#40]
![2019-01-17 10 46 45](https://user-images.githubusercontent.com/1025957/51289916-73d64a80-1a45-11e9-896d-57b946f2b1a7.png)

The proof lemma 9 uses the well-ordering principal on ordered set.
https://isabelle.in.tum.de/dist/library/HOL/HOL/Orderings.html
On the other hand, Isabelle has `linorder` (total order) type class in HOL.
We can define a kind of validator datatype and the instance of `linorder` on it?

ref:  https://github.com/cbc-casper/cbc-casper-paper/issues/14 says
```
The proof of Lemma 9 states that due to the "Well-Ordering Principle, a non-empty countable total order always has a minimal element". That's not true (e.g. (ℤ, ≤)), but it's also unneeded: Every finite, partially ordered non-empty set has at least one minimal element, which is sufficient for Lemma 9.
```
so actually `preorder` type class is needed?

**Comment by nrryuya** [comment]
Move to #59
