### ISSUE TITLE
[Paper] Choose the target conference

### ISSUE THREAD

**Issue by nrryuya** [LayerXcom/cbc-casper-proof#60]

**Comment by nud3l** [comment]
**Possible conferences**

Format: Name, tier, paper deadline, format, location, date

- [Cryptovalley}(https://www.cryptovalleyconference.com/technology-call-for-papers), Tier 3, March 15, full paper 10 pages/short paper 4 pages IEEE, Zug (Switzerland), June 24-26
- [ACM CCS](https://www.sigsac.org/ccs/CCS2019/index.php/call-for/call-for-papers/), Tier 1, May 15, full paper 12 pages ACM, London (UK), Nov 11-15
- [MARBLE](https://www.marble2019.org/), Workshop, Feb 25, 16 pages full/ 8 pages short LNCS, Santorini (Greece), May 6-10
- [BCC at AsiaCCS}(https://www.isical.ac.in/~bcc/bcc19/index), Workshop, Feb 15, full paper 10 pages ACM, Auckland (NZ), July 7
- {Asiacrpyt}(), Tier 2, TBD, TBD, TBD

**Comment by nud3l** [comment]
Focus on Cryptovalley (deadline March 15).
