### ISSUE TITLE
Set with function

### ISSUE THREAD

**Issue by nrryuya** [LayerXcom/cbc-casper-proof#8]
Why `{func a. a \<in> A}` is not parsed? Fow now, I'm using `{b. \<exists> a. b = func a /\ a = \<in> A}` instead.

**Comment by yudetamago** [comment]
MEMO:
https://isabelle.in.tum.de/dist/Isabelle2018/doc/prog-prove.pdf
3.2 Sets

`In {x . P} the x must be a variable. Set comprehension involving a proper term
t must be written {t | x y. P}, where x y are those free variables in t that occur
in P. This is just a shorthand for {v. ∃ x y. v = t ∧ P}, where v is a new variable.
For example, {x + y |x . x ∈ A} is short for {v. ∃ x . v = x+y ∧ x ∈ A}.`

**Comment by nrryuya** [comment]
`sum` can receive function.

```
(* Definition 2.11 *)
definition equivocation_fault_weight :: "weight \<Rightarrow> state \<Rightarrow> int"
  where
    "equivocation_fault_weight w s = sum w (equivocating_validators s)"
```

**Comment by nrryuya** [comment]
This worked well. Thanks!!!
```
(* Definition 7.7 *)
definition latest_justifications_from_honest_validators :: "state ⇒ validator ⇒ state set"
  where
    "latest_justifications_from_honest_validators s v = 
      {justification m | m. m ∈ latest_messages_from_honest_validators s v}"
```
